# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded Gui_AutoDock 	1.0 [list source [file join $dir Gui_AutoDock.tcl]]
package ifneeded Gui_AutoGrid 	1.0 [list source [file join $dir Gui_AutoGrid.tcl]]
package ifneeded AutoDock	1.0 [list source [file join $dir AutoDock.tcl]]
package ifneeded Gui_inputFile	1.0 [list source [file join $dir Gui_inputFile.tcl]]
package ifneeded Gui_Sasa	1.0 [list source [file join $dir Gui_Sasa.tcl]]
package ifneeded Gui_About      1.0 [list source [file join $dir Gui_About.tcl]]

