# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded VSLAB 		1.4 [list source [file join $dir/ vsLab.tcl]]
package ifneeded Gui_AutoDock   1.0 [list source [file join $dir/Routines/Lib/ Gui_AutoDock.tcl]]
package ifneeded Gui_AutoGrid   1.0 [list source [file join $dir/Routines/Lib/ Gui_AutoGrid.tcl]]
package ifneeded AutoDock       1.0 [list source [file join $dir/Routines/Lib/ AutoDock.tcl]]
package ifneeded Gui_inputFile  1.0 [list source [file join $dir/Routines/Lib/ Gui_inputFile.tcl]]
package ifneeded Gui_Sasa       1.0 [list source [file join $dir/Routines/Lib/ Gui_Sasa.tcl]]
package ifneeded Gui_About      1.0 [list source [file join $dir/Routines/Lib/ Gui_About.tcl]]
package ifneeded GuiVsLab       1.0 [list source [file join $dir/Routines/Lib/ Gui.tcl]]

# Load Sqlite
if {$::tcl_platform(os) == "Linux"} {
	if { $::tcl_platform(machine) == "i686" }   {
                load $dir/Routines/Other/sqlite/32B/tclsqlite-3.6.11.so
        } elseif { $::tcl_platform(machine) == "x86_64" } {
                load $dir/Routines/Other/sqlite/64B/libtclsqlite3.so}
} elseif {$::tcl_platform(os) == "Darwin"} {
	load $dir/Routines/Other/sqlite/MacOs/libsqlite3.6.18.dylib
} elseif {[string first "Windows" $::tcl_platform(os)] != -1} {
	load $dir/Routines/Other/sqlite/Windows/tclsqlite3.dll Sqlite3
}

